### PR TITLE
pt_BR strings

### PR DESCRIPTION
**Pull request by aevw**
Translated strings for PortAuthority in pt_BR.

### CODE REVIEW

**Comment by aevw** [comment]
First submitted in issue #144

**Comment by aaronjwood** [comment]
Thanks!

**Comment by aaronjwood** [comment]
Can you change this to go into the development branch instead of master?

**Comment by aevw** [comment]
sure thing

**Comment by aaronjwood** [comment]
Can you clean up your branch a bit too? There are 49 commits going into development here. It looks like you're trying to merge a branch based off master into development.

**Pull request closed without merging**
