### PR TITLE
Initial Italian translation

### PR DESCRIPTION
**Pull request by dantecpu**
Initial support for Italian localization of the app.

### CODE REVIEW

**Comment by aaronjwood** [comment]
> Permissions:
> 
> The following permissions need to be defined in AndroidManifest.xml:
> 
> android.permission.ACCESS_WIFI_STATE is necessary for calling WifiManager.getScanResults(). Without android.permission.CHANGE_WIFI_STATE you cannot initiate a scan with WifiManager.startScan().

Are you replying to the wrong issue here? Not sure what this has to do with your MR. I'm also not calling `WifiManager.getScanResults()` or `WifiManager.startScan()` anywhere in this codebase. Where did you get that from?

**Comment by aaronjwood** [comment]
Thanks for the translations!

**Comment by dantecpu** [comment]
> Permissions:
> 
> The following permissions need to be defined in AndroidManifest.xml:
> 
> android.permission.ACCESS_WIFI_STATE is necessary for calling WifiManager.getScanResults(). Without android.permission.CHANGE_WIFI_STATE you cannot initiate a scan with WifiManager.startScan().

That one was a reminder for me to shape the form of the translation at L52 into strings.xml, was a comment to a commit. Thanks for merging. Regards.

**Comment by aaronjwood** [comment]
Oh I see, I totally misunderstood :)

Thanks again!

**Pull request merged**
