### PR TITLE
Show IP on Main Activity Screen

### PR DESCRIPTION
**Pull request by thanset**
This pull request is only for showing the main wireless IP subnet, includes a fix for older Android devices.

### CODE REVIEW

**Comment by thanset** [comment]
Sure, go down to a /4? No idea who would have that but let's add it in

**Comment by aaronjwood** [comment]
How about down to a /1 http://www.rjsmith.com/CIDR-Table.html

You're right that most people probably won't ever have less than a /8 though!

**Comment by thanset** [comment]
Features: scan the entire internet with your phone.

**Comment by aaronjwood** [comment]
Hmm was thinking more about this. Since it'll be used for the host scanning maybe we keep it at /8 like you have it for now. There'd have to be some huge changes to how the threaded scanning is done and how the executors time out to handle so many hosts in a decent amount of time.

**Comment by aaronjwood** [comment]
Thanks for fixing this!

**Pull request merged**
